### ISSUE TITLE
Flask app closes

### ISSUE THREAD

**Issue by fabiansd** [acntech/RoboSchool#4]
The flask app container closes after brought up to life.

**Comment by loeiten** [comment]
Could not reproduce the error by following the instructions in the `README.md`. (I.e. it works for me).

**Comment by fabiansd** [comment]
The problem occurs when attempting to establish a volume connection between the container and the host. When the volume option is removed in docker-compose, I get the error message:

>  No module named app.__main__; 'app' is a package and cannot be directly executed

Since this is working on a Mac machine, this smells like a windows issue. Sigh

**Comment by fabiansd** [comment]
No longer relevant
